[package]
name = "liquid-derive"
version = "0.26.0"
authors = ["Pedro Gonçalo Correia <goncalerta@gmail.com>"]
description = "The liquid templating language for Rust"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/cobalt-org/liquid-rust"
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[lib]
proc-macro = true

[package.metadata.release]
pre-release-replacements = [
  {file="README.md", search="liquid-derive = \".*\"", replace="liquid-derive = \"{{version}}\"", exactly=1},
]

[dependencies]
syn = "1.0"
proc-quote = "0.4"
proc-macro2 = "1.0"
